[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dagster-webserver -h 0.0.0.0 -p $PORT -m dagster_pipeline"
healthcheckPath = "/server_info"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000

